title = "Captain Gregy"
baseURL = "https://captaingregy.github.io/site-content/"
# languageCode = "en-us"
theme = ["ananke"]
resourceDir = "../resources"

DefaultContentLanguage = "he"
SectionPagesMenu = "main"
Paginate = 10 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true
name = "Captain Gregy"

[languages]
  [languages.he]
    weight = 1
    contentDir = "content/he"
    languageDirection = 'rtl' # right to left

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"


[params.intro]
  main = "Captain Gregy"
  sub = "Anyone can be a Skipper"

[params.main]
  latestPublishHeader = " "

[params]
  custom_css = ["css/ad-text.css"]
  text_color = ""
  author = ""
  favicon = "favicon.png"
#  site_logo = "/images/logo.png"
  description = "Anyone can be a Skipper"
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 5
  mainSections = ["courses"]
    footer_email = "admin@captaingregy.com"
  footer_phone = "+972-549797752"
  footer_whatsapp = "https://wa.me/972549797752"
  footer_telegram = "https://t.me/c/1590458240/170"
  footer_address = "מעגן שביט רח’ הדייגים, חיפה"
  footer_logo = "images/logo.png"
  issa_logo = "images/ISSA.jpeg"
  [intro]
     name = "Captain Gregy"

[[params.ananke_socials]]
name = "facebook"
url = "https://www.facebook.com/CaptainGregy/"

[[params.ananke_socials]]
name = "instagram"
url = "https://www.instagram.com/captaingregy/"
